const BASE_URL = 'https://api.foursquare.com/v2/venues/';
const CLIENT_ID = '5LVDQ1WXKASZTIGBCR3E1LRGNFFYX5HEEKQQTN5H31LKGD5Q';
const CLIENT_SECRET = '3RSZIJRBAWJRVOOVHXXJX2NYMM0BTLCTUBKXUP1XVH2TOPAL';
const VERSION = '20180323';

export { BASE_URL, CLIENT_ID, CLIENT_SECRET, VERSION };